name: Deploy web-app
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install Packages
      run: npm install
    - name: Deploy to GH Pages
      run: npm run deploy
