name: Deploy live-server
on:
  push:
    branches:
      - master
    paths:
      - 'live-server/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build & push Docker image
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker build -t docker.io/dsaltares/doodle-live-server:latest .
        docker push dsaltares/doodle-live-server:latest
      working-directory: "./live-server"

    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_EC2_HOST }}
        username: ${{ secrets.AWS_EC2_USERNAME }}
        key: ${{ secrets.AWS_EC2_KEY }}
        script: |
          docker pull dsaltares/doodle-live-server
          docker stop doodle-live-server
          docker rm doodle-live-server
          docker run --name doodle-live-server -d -p 3000:3000 dsaltares/doodle-live-server
