name: Deploy live-server
on:
  push:
    branches:
      - master
    paths:
      - 'live-server/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v3
      working-directory: "./live-server"
      with:
        image: dsaltares/doodle-live-server
        tag: latest
        registry: docker.io
        dockerfile: Dockerfile.ci
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1

    - name: Pull Docker image from EC2
      uses: peterkimzz/aws-ssm-send-command
      with:
        instance_ids: ${{ secrets.EC2_INSTANCE_ID }}
        commands: docker pull dsaltares/doodle-live-server && \
          docker stop doodle-live-server && \
          docker rm doodle-live-server && \
          docker run --name doodle-live-server -d -p 3000:3000 dsaltares/doodle-live-server
