name: Deploy web-app
on:
  push:
    branches:
      - master
    paths:
      - 'web-app/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      working-directory: ./web-app
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install Packages
      run: yarn install
      working-directory: ${{env.working-directory}}
    - name: Build
      run: yarn build
      working-directory: ${{env.working-directory}}
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./web-app/build
