name: Deploy web-app
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./web-app
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install Packages
      run: yarn install
      working-directory: ${{env.working-directory}}
    - name: Setup git identity
      run: git config --global user.name "dsaltares" && git config --global user.email "david.saltares@gmail.com"
    - name: Deploy to GH Pages
      run: yarn deploy
      working-directory: ${{env.working-directory}}
